### ISSUE TITLE
For physical machines, / mavros / local_position/pose The X direction of position is inconsistent with the direction of building the map directly in front of the camera (90 degrees perpendicular to each other). How to solve this problem?

### ISSUE THREAD

**Issue by one-DS** [mzahana/px4_fast_planner#28]

**Comment by one-DS** [comment]
![2021-10-12 11-18-01 的屏幕截图](https://user-images.githubusercontent.com/60254680/136885634-fc80f33e-3afa-416d-9762-888c4640aa9f.png)

**Comment by one-DS** [comment]
![2021-10-12 11-13-26 的屏幕截图](https://user-images.githubusercontent.com/60254680/136885668-416b2178-3acd-45f7-845d-7714febe6be0.png)

**Comment by one-DS** [comment]
The map was originally built on the y-axis. I added a rotation, / mavros / local_ Position / pose also rotates together. If they do not rotate, they are also perpendicular to each other.

**Comment by one-DS** [comment]
@mzahana

**Comment by luccagandra** [comment]
I did a transform between world frame and map frame (<node pkg="tf" type="static_transform_publisher" name="world_map_linker" args="0 0 0 -1.57 0 0 world map 100" />), which fixed the problem, visually, in rviz. The problem is that, when I send a setpoint_position message, instead of the drone doing a 45 degrees rotation, it does a 135 degrees. It is probably because the rotation only occurs on Gazebo and on the pose of the drone and not inside of the Fast Planner node. Do you have any idea how to fix this problem? I'm using a custom Iris model...

**Comment by ZhangXiaolei314** [comment]
I am not suppoesed that you should change the params of static_transform_publisher

**Comment by Chai8226** [comment]
Hi, how you fix this proplem

**Comment by ZhangXiaolei314** [comment]
> 

I changed the index of "trans" and "rot" on the script px4_fast_planner/tree/master/scripts)/camera_pose_publisher.py , I supposed that you should change the order of the index
